[package]
name = "yellowstone-grpc-tools"
version = "1.0.0-rc.7+solana.1.17.5"
authors = { workspace = true }
edition = { workspace = true }
description = "Yellowstone gRPC Tools"
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
publish = false

[[bin]]
name = "grpc-google-pubsub"
required-features = ["google-pubsub"]

[[bin]]
name = "grpc-kafka"
required-features = ["kafka"]

[[bin]]
name = "grpc-plerkle"
required-features = ["plerkle"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
atty = { workspace = true }
chrono = { workspace = true, optional = true }
clap = { workspace = true }
const-hex = { workspace = true, optional = true }
flatbuffers = { workspace = true, optional = true }
futures = { workspace = true }
google-cloud-googleapis = { workspace = true, optional = true }
google-cloud-pubsub = { workspace = true, optional = true }
hyper = { workspace = true }
json5 = { workspace = true }
lazy_static = { workspace = true }
maplit = { workspace = true, optional = true }
plerkle_messenger = { workspace = true, optional = true }
plerkle_serialization = { workspace = true, optional = true }
prometheus = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha2 = { workspace = true, optional = true }
solana-sdk = { workspace = true, optional = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tonic-health = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
yellowstone-grpc-client = { workspace = true }
yellowstone-grpc-proto = { workspace = true }

[target.'cfg(not(all(target_os = "macos", target_arch = "aarch64")))'.dependencies]
rdkafka = { workspace = true, features = ["ssl"], optional = true }

[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))'.dependencies]
rdkafka = { workspace = true, features = ["ssl-vendored"], optional = true }

[build-dependencies]
anyhow = { workspace = true }
cargo-lock = { workspace = true }
git-version = { workspace = true }
vergen = { workspace = true }

[features]
default = ["google-pubsub", "kafka", "plerkle"]
google-pubsub = ["google-cloud-googleapis", "google-cloud-pubsub"]
kafka = ["const-hex", "rdkafka", "sha2"]
plerkle = ["chrono", "flatbuffers", "maplit", "plerkle_messenger", "plerkle_serialization", "solana-sdk"]
